name = "halsqa"
main = "src/index.ts"
compatibility_date = "2026-05-30"
assets = { directory = "./public" }

[[d1_databases]]
binding = "esol_marking_db"
database_name = "esol-marking-db-v2"
database_id = "b0293a0b-252e-4e15-844c-4a90b5821482"
