name = "esolqa"
main = "src/index.ts"
compatibility_date = "2026-05-30"
assets = { directory = "./public" }

[[d1_databases]]
binding = "esol_marking_db"
database_name = "esol-marking-db-v2"
database_id = "964d953b-08fb-4d88-837c-74e336902a38"
